### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by SasonBraha** [cloudhut/kowl#220]
Hi, first wanted to say thank you for the amazing work in this project.

I'm having a weird issue with Kowl after upgrading from 1.2.2 to 1.3.1. 
When visiting the page, there's a "Rendering Error!". The GUI works only after refreshing the page.
At first I thought it might be a caching issue that was fixed with the refresh, but I happens every time I visit the GUI on a new page. 
On Incognito - does not happen. I tried disabling all extensions, clearing all cache (local storage and such) but no luck. 
Note - the errors reports 1.2.2 and not 1.3.1, after reload the version is 1.3.1.

OS and Browser:
I'm using MacOS with Chrome version 90.0.4430.212 (Official Build) (x86_64)

Full Error:
```
Type:
TypeError

Message:
Expected a finite number, got undefined: undefined

Stack:
TypeError: Expected a finite number, got undefined: undefined
at e.exports (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:515797)
at R (http://localhost:9090/static/js/main.06522be4.chunk.js:1:3693)
at render (http://localhost:9090/static/js/main.06522be4.chunk.js:1:79824)
at http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:310360
at Yi (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1237571)
at Aa (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1245569)
at vc (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1286242)
at lu (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1276510)
at cu (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1276435)
at Zc (http://localhost:9090/static/js/2.ab6d81be.chunk.js:2:1273444)

Components:
in Cell
in tr
in BodyRow
in tbody
in Unknown
in table
in div
in div
in Unknown
in Unknown
in div
in Ne
in div
in div
in f
in div
in Er
in div
in a
in div
in ForwardRef
in a
in t
in t
in Pi
in ki
in Qi
in a
in main
in j
in Content
in section
in n
in Layout
in s
in section
in n
in Layout
in t
in t
in a
in a
in t
in t

Environment:
NODE_ENV : production
GIT_SHA  : 284eb140e520ee647f8801992c54e7ad05b3c0c3
GIT_REF  : v1.2.2
TIMESTAMP: 1606146599
appName  : Kowl

Location:
0       : [object Object]
1       : [object Object]
2       : [object Object]
3       : [object Object]
remove  : function(e){var t=this.indexOf(e);return-1!==t&&(this.splice(t,1),!0)}
removeAll: function(e){for(var t=0,a=0;a<this.length;a++)e(this[a])&&(this.splice(a,1),t++,a--);return t}
first   : function(e){var t,a=Object(w.a)(this);try{for(a.s();!(t=a.n()).done;){var n=t.value;if(e(n))return n}}catch(ll){a.e(ll)}finally{a.f()}}
last    : function(e){for(var t=this.length-1;t>=0;t--)if(!e||e(this[t]))return this[t]}
sum     : function(e){return this.reduce((function(t,a){return t+e(a)}),0)}
max     : function(e){return this.reduce((function(t,a){return Math.max(t,e(a))}),0)}
any     : function(e){var t,a=Object(w.a)(this);try{for(a.s();!(t=a.n()).done;){if(e(t.value))return!0}}catch(ll){a.e(ll)}finally{a.f()}return!1}
all     : function(e){var t,a=Object(w.a)(this);try{for(a.s();!(t=a.n()).done;){if(!e(t.value))return!1}}catch(ll){a.e(ll)}finally{a.f()}return!0}
groupBy : function(e){var t=new Map;return this.forEach((function(a){var n=e(a),r=t.get(n);r?r.push(a):t.set(n,[a])})),t}
groupInto: function(e){var t=this.groupBy(e),a=[];return t.forEach((function(e,t){a.push({key:t,items:e})})),a}
distinct: function(e){var t=e||function(e){return e},a=new Set,n=[];return this.forEach((function(e){var r=t(e);a.has(r)||(a.add(r),n.push(e))})),n}
pushDistinct: function(){for(var e=arguments.length,t=new Array(e),a=0;a<e;a++)t[a]=arguments[a];for(var n=0,r=t;n<r.length;n++){var i=r[n];this.includes(i)||this.push(i)}}
genericJoin: function(e){for(var t=[],a=1;a<this.length;a++){var n=this[a-1],r=e(n,this[a],a);t.push(n),t.push(r)}return t.push(this[this.length-1]),t}
toMap   : function(e,t){var a,n=new Map,r=Object(w.a)(this);try{for(r.s();!(a=r.n()).done;){var i=a.value,o=e(i),l=t(i);n.set(o,l)}}catch(ll){r.e(ll)}finally{r.f()}return n}
joinStr : function(e){var t,a="",n=Object(w.a)(this);try{for(n.s();!(t=n.n()).done;){var r=t.value;null!==r&&void 0!==r&&""!==r&&(0==a.length?a=r:a+=e+r)}}catch(ll){n.e(ll)}finally{n.f()}return a}
```

**Comment by weeco** [comment]
Hey @SasonBraha , I think that's because the SPA has not properly updated (error says it's still v1.2.2 while the backend probably served 1.3 compatible endpoints). This is something which we have fixed in 1.3 I think, so I hope the next update will be smoother.

**Comment by SasonBraha** [comment]
Hi @weeco, thank you for replying.
This was fixed after clearing the cache in chrome. I closed this issue and glad to know it is fixed in the newer release.
